services:
  - type: web
    name: antikontrafakt-quizbot
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
